### ISSUE TITLE
Weird hover diagnostic buffer behavior

### ISSUE THREAD

**Issue by DrPyser** [kak-lsp/kak-lsp#609] opened 2022-04-06 18:47 UTC
Hi! Thanks for this great tool!

I'm using latest version(12.1.0-snapshot).

I'm seeing flaky behavior with hover fifo buffers, working on python code(pyls).

Diagnostics/doc info often don't manage to stay in the buffer, they just blink in and out and the buffer ends up empty. After investigations, it seems that kak-lsp is repeating requests to the language server multiple times. That is, moving the cursor to a position once triggers a number of identical requests to the lsp server, and on each response kak-lsp reopens the buffer on the fifo, clearing it.

<details><summary>Log excerps</summary>
<p>

 ```
Apr 06 18:29:46.914 DEBG To server: {"jsonrpc":"2.0","method":"textDocument/hover","params":{"position":{"character":9,"line":37},"textDocument":{"uri":"file:///home/charles-langlois/repositories/microadobe/microadobe/microadobe/app.py"}},"id":771}, module: kak_lsp::language_server_transport:177
Apr 06 18:29:46.921 DEBG To server: {"jsonrpc":"2.0","method":"textDocument/hover","params":{"position":{"character":9,"line":37},"textDocument":{"uri":"file:///home/charles-langlois/repositories/microadobe/microadobe/microadobe/app.py"}},"id":772}, module: kak_lsp::language_server_transport:177
Apr 06 18:29:46.930 DEBG To server: {"jsonrpc":"2.0","method":"textDocument/hover","params":{"position":{"character":9,"line":37},"textDocument":{"uri":"file:///home/charles-langlois/repositories/microadobe/microadobe/microadobe/app.py"}},"id":773}, module: kak_lsp::language_server_transport:177
Apr 06 18:29:46.935 DEBG To server: {"jsonrpc":"2.0","method":"textDocument/documentHighlight","params":{"position":{"character":9,"line":37},"textDocument":{"uri":"file:///home/charles-langlois/repositories/microadobe/microadobe/microadobe/app.py"}},"id":774}, module: kak_lsp::language_server_transport:177
Apr 06 18:29:46.938 DEBG From server: {"jsonrpc":"2.0","id":771,"result":...}
Apr 06 18:29:46.948 DEBG From server: {"jsonrpc":"2.0","id":772,"result":...}
Apr 06 18:29:46.963 DEBG From server: {"jsonrpc":"2.0","id":773,"result":...}
Apr 06 18:29:47.027 DEBG To server: {"jsonrpc":"2.0","method":"textDocument/hover","params":{"position":{"character":9,"line":37},"textDocument":{"uri":"file:///home/charles-langlois/repositories/microadobe/microadobe/microadobe/app.py"}},"id":775}, module: kak_lsp::language_server_transport:177
Apr 06 18:29:47.031 DEBG To server: {"jsonrpc":"2.0","method":"textDocument/hover","params":{"position":{"character":9,"line":37},"textDocument":{"uri":"file:///home/charles-langlois/repositories/microadobe/microadobe/microadobe/app.py"}},"id":776}, module: kak_lsp::language_server_transport:177
Apr 06 18:29:47.034 DEBG To server: {"jsonrpc":"2.0","method":"textDocument/hover","params":{"position":{"character":9,"line":37},"textDocument":{"uri":"file:///home/charles-langlois/repositories/microadobe/microadobe/microadobe/app.py"}},"id":777}, module: kak_lsp::language_server_transport:177
Apr 06 18:29:47.039 DEBG To server: {"jsonrpc":"2.0","method":"textDocument/documentHighlight","params":{"position":{"character":9,"line":37},"textDocument":{"uri":"file:///home/charles-langlois/repositories/microadobe/microadobe/microadobe/app.py"}},"id":778}, module: kak_lsp::language_server_transport:177
Apr 06 18:29:47.063 DEBG From server: {"jsonrpc":"2.0","id":774,"result":...}
Apr 06 18:29:47.079 DEBG From server: {"jsonrpc":"2.0","id":776,"result":...}
Apr 06 18:29:47.091 DEBG From server: {"jsonrpc":"2.0","id":777,"result":...}
```

</p>
</details>

Thanks for any support!

**Comment by krobelus** [comment] 2022-04-06 19:44
> pyls

I recommend switching to the more actively maintained [`pylsp` AKA `python-lsp-server`](https://github.com/python-lsp/python-lsp-server) which is in the default config.

I don't know how to reproduce. Based on your description I'm guess you are using something like `lsp-auto-hover-enable client1` (while navigating in client0) which works just fine.

> After investigations, it seems that kak-lsp is repeating requests to the language server multiple times. That is, moving the cursor to a position once triggers a number of identical requests to the lsp server, and on each response kak-lsp reopens the buffer on the fifo, clearing it.

Good observation. I get redundant requests if I run `lsp-auto-hover-enable` multiple times but they're not destructive - because they each gets the same response - is that not the case for you?

**Comment by DrPyser** [comment] 2022-04-07 02:00
I meant pylsp, sorry.

In my case the buffer ends up empty most of the time.

**Comment by DrPyser** [comment] 2022-05-06 15:56
What would explain the behavior of repeated requests? Why isn't a single request sent to the LSP server?

**Comment by krobelus** [comment] 2022-05-06 16:35
> What would explain the behavior of repeated requests?

I get redundant requests if I run lsp-auto-hover-enable **multiple times**
Make sure your config only calls it once

**Comment by sclu1034** [comment] 2023-01-15 16:08
Presumably the same behaviour as #664.

**Comment by krobelus** [comment] 2023-01-15 16:22
yep, this should be fixed

**Closed by krobelus** 2023-01-15 16:22 UTC
Labels: need steps to reproduce
