### ISSUE TITLE
Julia unicodes

### ISSUE THREAD

**Issue by koehlerson** [kak-lsp/kak-lsp#444] opened 2021-01-27 15:08 UTC
The LanguageServer of Julia has unicode completion support e.g. `\xi` becomes `ξ` (full list here https://docs.julialang.org/en/v1/manual/unicode-input/index.html). 

`kak-lsp` does know about this, but it can't handle the completion/substitution, see:
![grafik](https://user-images.githubusercontent.com/27497290/106010491-cf6a5280-60b9-11eb-89de-54642e49c38e.png)

`\xi` is recognised but becomes:
![grafik](https://user-images.githubusercontent.com/27497290/106010546-df823200-60b9-11eb-9fbf-0871025e5536.png)

**Comment by clad26** [comment] 2021-02-05 16:59
I think this is more of a problem with unicode autocomplete....

**Comment by koehlerson** [comment] 2021-02-05 17:03
What do you mean by this? There are essentially 3 possible failing points. Kakoune, kak-lsp and the language server. Since kak-lsp recognises the capability of the LS, it should be related to either kakoune and kak-lsp. On the other hand I have no problems with kakoune dealing with unicodes, so it should be something in kak-lsp. However, I don't know the structure of kak-lsp to make any meaningful statement.

**Comment by clad26** [comment] 2021-02-05 17:57
Sorry, I meant unicode autocomplete in kakoune
Again, it might be the problem with kak-lsp

**Comment by koehlerson** [comment] 2021-08-09 12:59
I don't know what changed but under the current releases a few superscripts work as e.g. `\^h`

![grafik](https://user-images.githubusercontent.com/27497290/128709947-948983b3-1914-45c4-8d11-5328da9935b9.png)

**Comment by krobelus** [comment] 2021-10-29 18:15
LSP completions are served in two variants:
1. Completions that only contain the text to insert
2. Completions that are applied via a textEdit, which contains a range and a replacement text

Julia's Langserver's completion that replace `\xi` with `ξ` are sent as textEdits, because the first variant would't encode enough information to be able to delete the existing text (let's say `\x`) when inserting ξ.

Unfortunately, the second kind is not supported yet (#40).
I believe that with Kakoune's current completion engine it's not possible because Kakoune doesn't tell us enough about what happened to the text when navigating between completion candidates.

This issue made me realize another roadblock for #40:
Kakoune's completion engine will only show a completion candidate if the text at the cursor is actually a prefix of the completion candidate.

It would be very easy to support textEdit completions by having something like a `:menu ξ "exec aξ<esc>"` pop up.
Though that would open up some UI questions. Should we show the completions only on user request, or always?

The "on user request" variant should probably be exposed with :lsp-code-actions

Though it's better to always show completions. That will need some work on Kakoune because we need a completion widget with a few changes:
a. It should not filter away completions that don't match the text-at-cursor
b. When an option is selected, it should not insert anything but just execute a given command.

That being said, we could add another workaround so that when you type `\xi`, then selecting the completion will result in `\xiξ`... that would be easy but unsatisfactory.

**Comment by krobelus** [comment] 2021-11-01 16:22
Ok with a small change to Kakoune it wasn't so hard - https://github.com/kak-lsp/kak-lsp/pull/551 already works for completions like \xi. Please let me know if you find problems, I haven't tested it much.

**Comment by koehlerson** [comment] 2021-11-15 14:06
I'd like to give you feedback but somehow I can't get it to work. I compiled your kakoune fork on the linked branch and downloaded the kak-lsp repo and switched there to the PR branch as well. Now I finally switched in the kakrc config 
```
plug "kak-lsp/kak-lsp" do %{
# config stuff 
```
to 
```
plug "kak-lsp/kak-lsp" load-path "/home/mkoehler/tools/kak-lsp" do %{
# config stuff
```
Now, when I start a julia file, I only get:
kak-lsp: No actions available

**Comment by krobelus** [comment] 2021-11-15 16:20
Yeah, once you have compiled it, it should work. Just make sure that `which kak-lsp` points to the new binary.

I already thought about closing that Kakoune PR again, because so far the use cases have been limited to completion of unicode characters. It seems wrong to implement that feature inside Kakoune or kak-lsp.
Rather, the OS should provide a way to input Unicode characters.
Though maybe the Julia ones are nicer to use, so why not.

**Comment by koehlerson** [comment] 2021-11-15 16:25
I think that's not the case for me, since I get for `which kak-lsp` `/usr/bin/kak-lsp` which is probably my AUR installation. Can I somehow preserve my AUR installation and just override some environment variable in the kakrc config ?

**Comment by krobelus** [comment] 2021-11-15 16:32
Sure, you can start Kakoune like `PATH=path/to/kak-lsp/target/release:$PATH kak` (replace "release" with "debug" depending on which mode you built).
Or, more conventional, after the `cargo install`, `kak-lsp` should be installed to `~/.cargo/bin`, so just add that to your path.

**Comment by krobelus** [comment] 2021-11-17 16:56
I'll merge with some more small more changes. Let me know if you have some feedback, I have reasons for everything but didn't write everything down.

I just realized that the goto feature should probably be provided as a Kakoune text object.
Then people can user familiar bindings like `[X`, `{X`, `<a-i>X` and `<a-a>X` where X is our key for symbol/function/method.
Of course that's something for the future.
Let's find chars that are not used by the core or https://github.com/Delapouite/kakoune-text-objects

Anyway, the current changes are already great, it's really much nicer to use than stock Kakoune commands, especially when functions have long parameter lists and docstrings.

> You are deep within a huge function. You have forgotten the name of the function you are in or want to know what its parameters are.

Maybe it's more obvious to only provide the jump functionality (the user can use `<c-o>` to jump back).
Anyway, that's something to try for the future.

**Comment by krobelus** [comment] 2021-11-17 16:58
(wrong issue sorry)

**Comment by koehlerson** [comment] 2021-11-17 21:51
I really appreciate your efforts, that's why I'd love to give feedback but I'm still messing it up. I overwrote the `kak-lsp` path as suggested and checking `which` gives the correct path, but now the LanguageServer initializes all the time and is never in a ready state for me. If I start a new shell (without the overwritten PATH) everything works as expected. Debug buffer doesn't hold anything useful, just full of "init LS Server, parking request" statements

**Comment by krobelus** [comment] 2021-11-18 06:34
how are you sending the hover request?
This are the kak-lsp specific parts of my kakrc:

```kak
eval %sh{kak-lsp -s $kak_session --kakoune}
lsp-enable
```

and I start it like `PATH=path/to/kak-lsp/target/debug:$PATH kak test.jl` to debug a new kak-lsp

After waiting for a while, go-to-defintion works, as does `lsp-hover`.

I have Julia 1.6.3 and these packages:

```
julia> Pkg.installed()
┌ Warning: Pkg.installed() is deprecated
└ @ Pkg /build/julia/src/julia-1.6.3/usr/share/julia/stdlib/v1.6/Pkg/src/Pkg.jl:570
Dict{String, VersionNumber} with 3 entries:
  "StaticLint"     => v"8.0.1"
  "LanguageServer" => v"4.1.0"
  "SymbolServer"   => v"7.0.1"
```

That error message sounds like a bug in the language server. It's valid to return no response, the logs would look like this:

```
Nov 18 07:32:29.450 DEBG To server: {"jsonrpc":"2.0","method":"textDocument/hover","params":{"position":{"character":3,"line":10},"textDocument":{"uri":"file:///home/johannes/git/kak-lsp/test.jl"}},"id":5}, module: kak_lsp::language_server_transport:177
Nov 18 07:32:29.537 DEBG From server: {"id":5,"jsonrpc":"2.0","result":null}, module: kak_lsp::language_server_transport:151
```

**Comment by koehlerson** [comment] 2021-11-18 18:26
alright I'm now on the same version of `StaticLint`, `LanguageServer` and `SymbolServer`. I get the following behavior:

![image](https://user-images.githubusercontent.com/27497290/142474051-d8844963-56b1-4983-97f2-ea1a4264e2e0.png)

All autocomplete candidates are recognized and the completion is right next to the completion menu, but the actual substitution doesn't work for me. Here is my kak-lsp config from my kakrc

```
plug "kak-lsp/kak-lsp" do %{
#    cargo build --release --locked
#    cargo install --force --path .
    ln -sf $PWD/target/release/kak-lsp ~/tools/kak-lsp/target/release/kak-lsp --locked --force --path .
} config %{
    # uncomment to enable debugging
    #eval %sh{echo ${kak_opt_lsp_cmd} >> /tmp/kak-lsp.log}
    #set global lsp_cmd "kak-lsp -s %val{session} -vvv --log /tmp/kak-lsp.log"

    # this is not necessary; the `lsp-enable-window` will take care of it
    # eval %sh{${kak_opt_lsp_cmd} --kakoune -s $kak_session}

    set global lsp_diagnostic_line_error_sign '║'
    set global lsp_diagnostic_line_warning_sign '┊'
    set global lsp_hover_max_lines 22
    define-command ne -docstring 'go to next error/warning from lsp' %{ lsp-find-error --include-warnings }
    define-command pe -docstring 'go to previous error/warning from lsp' %{ lsp-find-error --previous --include-warnings }
    define-command ee -docstring 'go to current error/warning from lsp' %{ lsp-find-error --include-warnings; lsp-find-error --previous --include-warnings }

    define-command lsp-restart -docstring 'restart lsp server' %{ lsp-stop; lsp-start }
    hook global WinSetOption filetype=(c|cpp|cc|rust|javascript|typescript|julia) %{
        set-option window lsp_hover_anchor false
        lsp-auto-hover-enable
        echo -debug "Enabling LSP for filtetype %opt{filetype}"
        lsp-enable-window
    }

    hook global KakEnd .* lsp-exit
}

```

**Comment by krobelus** [comment] 2021-11-18 19:03
On Thu, Nov 18, 2021 at 10:26:38AM -0800, Maximilian Köhler wrote:
> alright I'm now on the same version of `StaticLint`, `LanguageServer` and `SymbolServer`. I get the following behavior:
> 
> ![image](https://user-images.githubusercontent.com/27497290/142474051-d8844963-56b1-4983-97f2-ea1a4264e2e0.png)
> 
> All autocomplete candidates are recognized and the completion is right next to the completion menu, but the actual substitution doesn't work for me. Here is my kak-lsp config from my kakrc

no idea what's going on yet. Can you post a debug log? That will show if the completions are set correctly.

Ok so Kakoune is inserting `\xi` instead of the ξ, hence the double backslash?

Can you make sure that "echo %opt{lsp_have_kakoune_feature_filtertext}" shows "true"?
If it's false, that means your Kakoune version doesn't support the extended completion format.

> 
> ```
> plug "kak-lsp/kak-lsp" do %{
> #    cargo build --release --locked
> #    cargo install --force --path .
>     ln -sf $PWD/target/release/kak-lsp ~/tools/kak-lsp/target/release/kak-lsp --locked --force --path .

there are leftover args here, so I think "ln" will error here

Honestly, please just try configuring *without* plug.kak.
That's less complicated -- it's just two lines -- and harder to mess up (see below).

> } config %{
>     # uncomment to enable debugging
>     #eval %sh{echo ${kak_opt_lsp_cmd} >> /tmp/kak-lsp.log}
>     #set global lsp_cmd "kak-lsp -s %val{session} -vvv --log /tmp/kak-lsp.log"
> 
>     # this is not necessary; the `lsp-enable-window` will take care of it
>     # eval %sh{${kak_opt_lsp_cmd} --kakoune -s $kak_session}

the "`lsp-enable-window` will take care of it" bit is off, actually plug.kak
will automatically load all *.kak files in the plugin's directory (rc/lsp.kak
is equivalent to the output of "kak-lsp --kakoune").

So this means that you are loading ~/.config/kak/plugins/kak-lsp/rc/lsp.kak - make sure that it's the one you want.
You can change branches in ~/.config/kak/plugins/kak-lsp but eventually you'd give control back to plug.kak (you can also tell it to use a specific branch/commit)

> 
>     set global lsp_diagnostic_line_error_sign '║'
>     set global lsp_diagnostic_line_warning_sign '┊'
>     set global lsp_hover_max_lines 22
>     define-command ne -docstring 'go to next error/warning from lsp' %{ lsp-find-error --include-warnings }
>     define-command pe -docstring 'go to previous error/warning from lsp' %{ lsp-find-error --previous --include-warnings }
>     define-command ee -docstring 'go to current error/warning from lsp' %{ lsp-find-error --include-warnings; lsp-find-error --previous --include-warnings }
> 
>     define-command lsp-restart -docstring 'restart lsp server' %{ lsp-stop; lsp-start }

since these commands are async, I'm not sure if this works well. I sometimes use lsp-disable followed by lsp-enable

>     hook global WinSetOption filetype=(c|cpp|cc|rust|javascript|typescript|julia) %{
>         set-option window lsp_hover_anchor false
>         lsp-auto-hover-enable
>         echo -debug "Enabling LSP for filtetype %opt{filetype}"
>         lsp-enable-window
>     }
> 
>     hook global KakEnd .* lsp-exit

This should be done automatically

**Comment by koehlerson** [comment] 2021-11-18 19:43
Ok I followed your recommendations and cleaned up the config and just inserted your two commands. It works now to some extend. When I try to call \bf something the LS crashes
![kakoune](https://user-images.githubusercontent.com/27497290/142485902-62adb98f-e7a4-48ce-96a5-5a3f9cc02c61.gif)

**Comment by krobelus** [comment] 2021-11-18 20:01
interesting, I can reproduce after typing a couple of these.
Probably the language server gives up if there are too many syntax errors?

**Comment by koehlerson** [comment] 2021-11-18 20:03
I think that's the case. @pfitzseb is it possible that the LS crashes because of multiple errors?

**Comment by krobelus** [comment] 2021-11-18 20:09
It doesn't crash for me, I just get `{"id":156,"jsonrpc":"2.0","result":{"isIncomplete":true,"items":[]}}` as response to `textDocument/completion` when typing a bunch of syntax errors followed by `\bf`

**Comment by pfitzseb** [comment] 2021-11-18 20:22
The LS should be fairly robust against syntax errors. Would be very helpful to get some logs for this. Also, are you on master of all LS related packages? The released versions don't work atm, I think.

**Comment by koehlerson** [comment] 2021-11-18 20:23
ah no, let me try with master. I'm on the same version as @krobelus atm

**Comment by koehlerson** [comment] 2021-11-18 20:48
same behavior on master for me. I think this is the relevant piece of the log file :
```ERROR: get_offset crashed. More diagnostics:
line=4
character=11
position(io)=65
line_offsets='[0, 17, 32, 36, 37, 65]'
text='aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaa
aaa

α——a—a𝐅a𝕱aaaaa
'

original_error=ERROR: EOFError: read end of file
Stacktrace:
 [1] read
   @ ./iobuffer.jl:217 [inlined]
 [2] read(io::IOBuffer, #unused#::Type{Char})
   @ Base ./io.jl:750
 [3] get_offset(doc::LanguageServer.Document, line::Int64, character::Int64)
   @ LanguageServer ~/.julia/packages/LanguageServer/zmm2K/src/document.jl:82
 [4] get_offset
   @ ~/.julia/packages/LanguageServer/zmm2K/src/document.jl:101 [inlined]
 [5] textDocument_completion_request(params::LanguageServer.CompletionParams, server::LanguageServerInstance, conn::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint})
   @ LanguageServer ~/.julia/packages/LanguageServer/zmm2K/src/requests/completions.jl:44
 [6] (::LanguageServer.var\\\"#97#98\\\"{typeof(LanguageServer.textDocument_completion_request), LanguageServerInstance})(conn::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, params::LanguageServer.CompletionParams)
   @ LanguageServer ~/.julia/packages/LanguageServer/zmm2K/src/languageserverinstance.jl:251
 [7] dispatch_msg(x::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, dispatcher::JSONRPC.MsgDispatcher, msg::Dict{String, Any})
   @ JSONRPC ~/.julia/packages/JSONRPC/yu0G3/src/typed.jl:67
 [8] run(server::LanguageServerInstance)
   @ LanguageServer ~/.julia/packages/LanguageServer/zmm2K/src/languageserverinstance.jl:365
 [9] top-level scope
   @ none:8

Stacktrace:
 [1] get_offset(doc::LanguageServer.Document, line::Int64, character::Int64)
   @ LanguageServer ~/.julia/packages/LanguageServer/zmm2K/src/document.jl:98
 [2] get_offset
   @ ~/.julia/packages/LanguageServer/zmm2K/src/document.jl:101 [inlined]
 [3] textDocument_completion_request(params::LanguageServer.CompletionParams, server::LanguageServerInstance, conn::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint})
   @ LanguageServer ~/.julia/packages/LanguageServer/zmm2K/src/requests/completions.jl:44
 [4] (::LanguageServer.var\\\"#97#98\\\"{typeof(LanguageServer.textDocument_completion_request), LanguageServerInstance})(conn::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, params::LanguageServer.CompletionParams)
   @ LanguageServer ~/.julia/packages/LanguageServer/zmm2K/src/languageserverinstance.jl:251
 [5] dispatch_msg(x::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, dispatcher::JSONRPC.MsgDispatcher, msg::Dict{String, Any})
   @ JSONRPC ~/.julia/packages/JSONRPC/yu0G3/src/typed.jl:67
 [6] run(server::LanguageServerInstance)
   @ LanguageServer ~/.julia/packages/LanguageServer/zmm2K/src/languageserverinstance.jl:365
 [7] top-level scope
   @ none:8

caused by: EOFError: read end of file
Stacktrace:
 [1] read
   @ ./iobuffer.jl:217 [inlined]
 [2] read(io::IOBuffer, #unused#::Type{Char})
   @ Base ./io.jl:750
 [3] get_offset(doc::LanguageServer.Document, line::Int64, character::Int64)
   @ LanguageServer ~/.julia/packages/LanguageServer/zmm2K/src/document.jl:82
 [4] get_offset
   @ ~/.julia/packages/LanguageServer/zmm2K/src/document.jl:101 [inlined]
 [5] textDocument_completion_request(params::LanguageServer.CompletionParams, server::LanguageServerInstance, conn::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint})
   @ LanguageServer ~/.julia/packages/LanguageServer/zmm2K/src/requests/completions.jl:44
 [6] (::LanguageServer.var\\\"#97#98\\\"{typeof(LanguageServer.textDocument_completion_request), LanguageServerInstance})(conn::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, params::LanguageServer.CompletionParams)
   @ LanguageServer ~/.julia/packages/LanguageServer/zmm2K/src/languageserverinstance.jl:251
 [7] dispatch_msg(x::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, dispatcher::JSONRPC.MsgDispatcher, msg::Dict{String, Any})
   @ JSONRPC ~/.julia/packages/JSONRPC/yu0G3/src/typed.jl:67
 [8] run(server::LanguageServerInstance)
   @ LanguageServer ~/.julia/packages/LanguageServer/zmm2K/src/languageserverinstance.jl:365
 [9] top-level scope
   @ none:8
, module: kak_lsp::language_server_transport:58
Nov 18 21:44:49.109 INFO Waiting for Messages to language server to finish..., module: kak_lsp::thread_worker:19
Nov 18 21:44:49.109 DEBG Received signal to stop language server, closing pipe, module: kak_lsp::language_server_transport:188
Nov 18 21:44:49.109 DEBG Waiting for language server process end, module: kak_lsp::language_server_transport:87
Nov 18 21:44:50.109 INFO ... Messages to language server terminated with ok, module: kak_lsp::thread_worker:21
Nov 18 21:44:50.109 INFO Waiting for Messages from language server to finish..., module: kak_lsp::thread_worker:19
Nov 18 21:44:50.109 INFO ... Messages from language server terminated with ok, module: kak_lsp::thread_worker:21
Nov 18 21:44:50.109 INFO Waiting for Language server errors to finish..., module: kak_lsp::thread_worker:19
Nov 18 21:44:50.109 INFO ... Language server errors terminated with ok, module: kak_lsp::thread_worker:21
```
[kak-lsp.log](https://github.com/kak-lsp/kak-lsp/files/7565881/kak-lsp.log)
This is the full log file

**Comment by koehlerson** [comment] 2021-11-19 14:12
I used the new versions of kak and kak-lsp the whole day for work and the LS never crashed for me. Seems like the above reported behavior is a pretty edge case. @krobelus thanks for the PR, I'm really enjoying the new feature :)

**Closed** 2021-11-24 19:47 UTC

**Comment by krobelus** [comment] 2021-11-24 19:50
sounds great, I merged the kak-lsp feature. Probably you'll have to carry the Kakoune patch for a while, but it's fairly small and I'll rebase it when needed (I'm also using it).
