### ISSUE TITLE
Wrong cursor placement when using snippets

### ISSUE THREAD

**Issue by Tanish2002** [kak-lsp/kak-lsp#463] opened 2021-02-27 13:01 UTC
Hello I am new to kakoune and trying out kak-lsp but when using `snippet_support = true` the cursor placement is kinda off like if I type `println` and then start typing the thing that is supposed to be printed the cursor placement is kinda off and wack, I don't how to explain this so I'll link a video
http://0x0.st/-K_v.mp4
In this video you can see that when I typed `"` it didn't place it in the right place

also this is not golang specific and happens in rust as well with rust-analyzer
my `kak-lsp.toml` -:
```
snippet_support = true
...
[language.go]
filetypes = ["go"]
roots = ["Gopkg.toml", "go.mod", ".git", ".hg"]
command = "gopls"
formatTool = "gofmt"
offset_encoding = "utf-8"
...
```
my `kakrc` :-
```
...
eval %sh{kak-lsp --kakoune -s $kak_session}
lsp-enable
lsp-auto-hover-enable
...
```

**Comment by krobelus** [comment] 2021-02-28 18:34
Thanks for the clear description -  for now it is better to disable snippet support. Looks like we already have an issue, so let's just reference this one.

**Comment by krobelus** [comment] 2021-02-28 18:34
Duplicate of #282

**Closed by krobelus** 2021-02-28 18:34 UTC

**Comment by krobelus** [comment] 2021-03-06 18:09
Actually there is a [mapping in the README](https://github.com/kak-lsp/kak-lsp#snippets) that works around this issue. YMMV

**Comment by TuM0xA-S** [comment] 2021-07-24 08:22
thx now it works. sorry for colors in recording(problems with true color)
