### ISSUE TITLE
Language server is not configured for filetype ``

### ISSUE THREAD

**Issue by InfRandomness** [kak-lsp/kak-lsp#462] opened 2021-02-23 09:39 UTC
Hi, I'm new to kak and kak-lsp, I'm trying to setup C completion on kak using kak-lsp, however I'm having a few issues : 

I tried doing "kak-lsp -vvvv --session session" in a window and then "kak -s session file.c" + lsp-capabilities (in kak)

the kak-lsp window reported me this : 
```
Feb 23 10:19:54.599 DEBG Language server is not configured for filetype ``, module: kak_lsp::session:80
```

I'm not sure what if I have configured something wrong or if this is a possible bug.

configuration files : 
kakrc : 
```
eval %sh{kak-lsp --kakoune -s $kak_session}
hook global WinSetOption filetype=(c|cpp|zig) %{
    lsp-enable-window
    lsp-auto-hover-enable
    lsp-auto-signature-help-mode
    lsp-auto-hover-insert-mode-disable
}
```
kak-lsp :
```toml
snippet_support = false
verbosity = 2

[server]
# exit session if no requests were received during given period in seconds
# works only in unix sockets mode (-s/--session)
# set to 0 to disable
timeout = 1800 # seconds = 30 minutes

[language.c_cpp]
filetypes = ["c", "cpp"]
roots = ["compile_commands.json", ".clangd"]
command = "clangd"

[language.zig]
filetypes = ["zig"]
roots = ["build.zig"]
command = "zls"
```
my environment : 
OS : ArchLinux
kak : Kakoune v2020.09.01
kak-lsp : kak-lsp 9.0.0
clangd : clangd version 11.1.0

Thanks in advance.

**Comment by krobelus** [comment] 2021-02-23 17:25
> Language server is not configured for filetype

Looks like Kakoune fails to detect the file type.
If it does, the first three lines of the -vvv log should be like

```
Feb 23 18:17:16.271 INFO Starting main event loop, module: kak_lsp::session:29
Feb 23 18:17:16.272 DEBG Searching for vars starting with KAK_LSP_PROJECT_ROOT_C_CPP, module: kak_lsp::project_root:46
Feb 23 18:17:16.273 DEBG Routing editor request to Route { session: "foo", language: "c_cpp", root: "/home/johannes" }, module: kak_lsp::session:95
```

Can you try launching Kakoune without other configuration - for example

```sh
$ HOME=$(mktemp -d) kak -s session file.c -e 'echo %opt{filetype}'
```

The `:echo %opt{filetype}` should display "c" in the prompt.
Kakoune's [file.kak](https://github.com/mawww/kakoune/blob/master/rc/detection/file.kak) should be active and set this file type automatically. It requires you to have the `file` program installed (which is part of `base-devel`).

**Comment by InfRandomness** [comment] 2021-02-23 17:31
Here is the full logs of kak-lsp (-vvv) (it gets printed if I run lsp-capabilities) : 
```
Feb 23 18:30:31.340 DEBG From editor:
session  = "session"
client   = "client0"
buffile  = "/home/infrandomness/Documents/Epitech/tek1/mysokoban/src/main.c"
filetype = ""
version  = 1
method   = "capabilities"
[params]
, module: kak_lsp::editor_transport:122
Feb 23 18:30:31.341 DEBG Language server is not configured for filetype ``, module: kak_lsp::session:80
```

**Comment by krobelus** [comment] 2021-02-23 17:58
You should first debug without `kak-lsp`, because the problem seems to be the wrongly-detected filetype.

Open `file.c` and run `:echo %opt{filetype}` - if this does not print `c`, then we need to fix that.

`:set-option window filetype c` might fix it for the active buffer, but that should happen automatically.

I believe if you launch kak-lsp manually, it keeps running; I'm not sure.

**Comment by InfRandomness** [comment] 2021-02-23 18:59
> I believe if you launch kak-lsp manually, it keeps running; I'm not sure.
it exited when I exited kak

**Comment by krobelus** [comment] 2021-02-23 20:14
> so the filetype is detected and correct

OK; then `:lsp-capabilities` must produce a log statement like `filetype = "c"` (as opposed to your previous `filetype = ""`)
Also when you open the file you should get a line containing `Routing editor request to Route { session: "foo", language: "c_cpp"` in the log.

Assuming the above statements hold - which means that kak-lsp works with a temporary home - my guess is that there is something in your other config that disables the filetype.
Are you setting `disabled_hooks`? Did you override the `autoload` directory?
Try commenting everything in your kakrc except for the kak-lsp bits to narrow it down.

**Comment by InfRandomness** [comment] 2021-02-23 20:18
> Are you setting disabled_hooks?

No

> Did you override the autoload directory?

All the things you see in the codeblocks of the first message is all of what I've got, and everything looks to be related to kak-lsp, I don't know what to comment

**Comment by krobelus** [comment] 2021-02-23 21:10
I think I found it - `lsp-auto-signature-help-mode` is wrong, it should rather be `lsp-auto-signature-help-enable` 

First rule of Kakoune debugging: check the `*debug*` buffer for errors :face_with_head_bandage:

**Comment by InfRandomness** [comment] 2021-02-23 21:10
the buffer was empty, I have checked multiple times

**Comment by krobelus** [comment] 2021-02-23 21:12
If you run `:lsp-auto-signature-help-mode` it won't be empty.

**Comment by InfRandomness** [comment] 2021-02-23 21:13
I have changed it, but it is still not detecting the filetype

**Comment by krobelus** [comment] 2021-02-23 21:16
Okay it wasn't the wrong command.

Here is a Dockerfile with your config. This works for me - run `kak test.c` - the log will be in `~/log`.

```Dockerfile
FROM docker.io/archlinux:latest

RUN pacman -Sy
RUN pacman -S --noconfirm kakoune kak-lsp clang

RUN groupadd -g 1000 user \
  && useradd -p $(openssl passwd -1 fish) -d /home/user -m -u 1000 -g 1000 user

USER user
WORKDIR /home/user

RUN mkdir -p ~/.config/kak/ && printf '%s\n' >~/.config/kak/kakrc \
	'eval %sh{kak-lsp --kakoune -s $kak_session}' \
	'set global lsp_cmd "kak-lsp -s %val{session} -vvvv --log /home/user/log"' \
	'hook global WinSetOption filetype=(c|cpp|zig) %{' \
	'    lsp-enable-window' \
	'    lsp-auto-hover-enable' \
	'    nop TODO the below command is wrong, but it does not seem to matter' \
	'    lsp-auto-signature-help-mode' \
	'    lsp-auto-hover-insert-mode-disable' \
	'}'

RUN mkdir -p ~/.config/kak-lsp && printf '%s\n' >~/.config/kak-lsp/kak-lsp.toml \
	'snippet_support = false' \
	'verbosity = 2' \
	'[server]' \
	'# exit session if no requests were received during given period in seconds' \
	'# works only in unix sockets mode (-s/--session)' \
	'# set to 0 to disable' \
	'timeout = 1800 # seconds = 30 minutes' \
	'[language.c_cpp]' \
	'filetypes = ["c", "cpp"]' \
	'roots = ["compile_commands.json", ".clangd"]' \
	'command = "clangd"' \
	'[language.zig]' \
	'filetypes = ["zig"]' \
	'roots = ["build.zig"]' \
	'command = "zls"'

RUN printf '%s\n' >test.c \
	'void bar() { }' \
	'void foo() { bar(); }'
```

**Comment by InfRandomness** [comment] 2021-02-23 21:22
This works on my side too, logs : https://paste.opensuse.org/5435998

**Comment by krobelus** [comment] 2021-02-23 21:29
Yes - the point of the container is that it works the same way anywhere.

What you'd need to do know is find out what is different between your system and the container.
Maybe you have overridden the `file` command or something.
A basic sanity check would be to run `kak somefile.c -e 'echo %opt{filetype}'` - I'm still not sure if that correctly prints `c` when you are not using a temporary $HOME.

**Comment by InfRandomness** [comment] 2021-02-23 21:31
> kak somefile.c -e 'echo %opt{filetype}'

Prints nothing

**Comment by krobelus** [comment] 2021-02-23 21:33
Ok, I think we're close.

The detection is implemented in [file.kak](https://github.com/mawww/kakoune/blob/master/rc/detection/file.kak), so what is the output of
`file -b --mime-type -L somefile.c`

**Comment by InfRandomness** [comment] 2021-02-23 21:39
wait, so.. I've uninstalled kakoune and kak-rls using pacman -Rs (delete package, configuration, ..), deleted the config files in my home folder, reinstalled them using pacman -S kakoune kak-rls and then rewrote the configuration files, and it looks like it works now..

 > file -b --mime-type -L somefile.c

text/x-c

**Comment by krobelus** [comment] 2021-02-23 21:42
Cool - please reopen if you can reproduce.

(on a second thought, the filetype is actually set by `/usr/share/kak/rc/filetype/c-family.kak`, not file,kak)

**Closed by krobelus** 2021-02-23 21:42 UTC
Labels: need steps to reproduce

**Comment by InfRandomness** [comment] 2021-03-11 13:29
So uh, I re open this issue because this is happening again on my other computer I've just installed fedora (33) on, and I ran all the steps above, doing all the steps above did not resolve the issue, the exact same problem is happening where kak-lsp prints : 
```
Feb 23 10:19:54.599 DEBG Language server is not configured for filetype ``, module: kak_lsp::session:80
```
I do not understand how to solve this problem once and for all

**Comment by krobelus** [comment] 2021-03-11 18:29
As said above, this is not an error in kak-lsp - your `%opt{filetype}` is wrong. Try to narrow down the differences between the non-working setup and a working one.

**Comment by InfRandomness** [comment] 2021-03-11 21:42
I'm not sure what's going on here, I have the same configuration files both in a docker container, and it works (I've copied from here : https://github.com/kak-lsp/kak-lsp/issues/462#issuecomment-784518338), but on my host it doesn't

**Comment by UltraBlackLinux** [comment] 2022-12-25 12:22
Weirdly I'm facing the same issue too. Same error, but my `:echo %opt{filetype}` is set correctly, but `:lsp-capabilities` also doesn't return anything. The debug buffer shows four detected config changes (which did not happen)

My config is located in .config/kak-lsp/kak-lsp.toml and I installed it via the aur, because it failed via plug (127 - whatever that means)

[kakrc.txt](https://github.com/kak-lsp/kak-lsp/files/10299926/kakrc.txt)
[kak-lsp.toml.txt](https://github.com/kak-lsp/kak-lsp/files/10299928/kak-lsp.toml.txt)

I have absolutely no clue what could be causing this.

**Comment by krobelus** [comment] 2022-12-25 15:53
@UltraBlackLinux I can't reproduce, your config works for me on a C file.
Consider providing a full reproducer (maybe a docker file).
Also, it's unlikely that the information in this thread will help us here, so it's better to open a separate issue.

One problematic thing about your config is that you call both `lsp-enable` and `lsp-enable-window`, which results in redundant diagnostics etc.; you only need one.
I also recommend trying the default `kak-lsp.toml` (i.e. just delete yours)

**Comment by edef1c** [comment] 2022-12-26 22:54
I'm experiencing this exact error, and `:echo %opt{filetype}` (and the visibly working syntax highlighting) indicate that the filetype is detected just fine. I'm open to the possibility that my `init.kak` is otherwise broken, but kak-lsp is the only thing that's misbehaving in any way I can detect.

**Comment by edef1c** [comment] 2022-12-26 22:56
Notably, it seems to produce this message on files where the LSP *does* work as well, so it's not actually correlated with the issue I'm debugging. Specifically, I'm debugging my Haskell LSP, but Go produces the same message despite the LSP working fine there.

**Comment by edef1c** [comment] 2022-12-26 23:01
After replacing the naked `lsp-enable` with `hook global WinSetOption filetype=* lsp-enable` it seems to go away, and everything that worked before still does. Presumably `filetype` is initialised later, so it's still unset when `lsp-enable` is called at init time?

**Comment by krobelus** [comment] 2022-12-27 15:07
@edef1c Does it happen with the [default config](https://github.com/kak-lsp/kak-lsp/#default-configuration)?
Can you give steps to reproduce? It should be easy to comment out stuff from your init.kak to find a the minimal config that exposes the problem.

>  hook global WinSetOption filetype=* lsp-enable

This is an odd setup, you should either run `lsp-enable` once, or `lsp-enable-window` in all windows you care about.
It still works but every new `lsp-enable` adds errors to the `*debug*` buffer.

Also `filetype=*` looks like a mistake; it will only ever match the *empty* filetype (e.g. `*scratch*` buffer, or plain text files).
You want something like `filetype=.*` (or `filetype=` if you want to match the empty filetype)

---

I'm starting to think that  ```Language server is not configured for filetype `` ```
is a legit warning. It happens if you run LSP commands in a buffer with the empty filetype.
Since 15d29970 (Show unconfigured filetype errors in editor, 2022-07-22) we show it in the
editor, but only if the request does not come from a hook. This means that you are probably
running some LSP command interactively.

> Presumably filetype is initialised later, so it's still unset when lsp-enable is called at init time?

Which file does it happen one and how do you run lsp-enable?
Usually, a `BufCreate` hook takes care of setting filetype `foo`, which triggers a `WinSetOption=foo` hook to enable LSP.
So there should be no ordering issue.
Regardless, this should really not be related to this problem. It should work the same way with `lsp-enable`.
