### ISSUE TITLE
No Rust completions for fields/methods

### ISSUE THREAD

**Issue by malte-v** [kak-lsp/kak-lsp#464] opened 2021-02-27 19:07 UTC
When using rust-analyzer or rls, the completions work in principle; however they only work at the beginning of statements/expressions. That is, when writing something like `somevar.`, there are no completions after the dot, and when I continue typing, it falls back to Kakoune's "dumb" text-based completion. To me the completions for fields/methods are the most useful ones and not having them is kind of a pain.

**Comment by malte-v** [comment] 2021-02-27 19:12
Oops, turns out it was my sloppy code. Sorry for opening the issue.

**Comment by malte-v** [comment] 2021-02-27 20:54
Oops again, turns out it was not my sloppy code. The rust-analyzer VSCode extension gives completions after the accessor dot, while kak-lsp does not.

**Comment by krobelus** [comment] 2021-03-13 17:15
>  when writing something like somevar., there are no completions after the dot

I can reproduce with `rust-analyzer`, but it works fine with `rls` (which seems much more stable)

**Comment by krobelus** [comment] 2021-03-14 16:58
Hmm I can't reproduce anymore - but I observed that rust-analyzer is a bit slow sometimes
I'm using rust-analyzer 20210308.

Can you reproduce with below script - by default it should print the completions from rust-analyzer like so

```shell
$ ./repro.sh
fn test() {
        let x = SomeStruct{some_field: false};
        x.
}         into       Method█
~         some_field Field █
```

Run as `INTERACTIVE=true ./repro.sh` to automatically attach into the tmux session, so you can play around.

<details>

```sh
#!/bin/sh

# REQUIRES: command -v rust-analyzer

{ # Braces to get predictable behavior when editing this file while it's running.

# Change to a new HOME and sets $tmux and $kak_startup_commands.

set -e

# This test requires tmux.
command -v tmux >/dev/null

# Export a fresh HOME, so Kakoune is run without user configuration.
HOME=$(mktemp -d)
cd "$HOME"

# Isolated tmux.
tmux="tmux -S $HOME/.tmux-socket -f $HOME/.tmux.conf"

kak_startup_commands="
	evaluate-commands %sh{kak-lsp --kakoune -s \$kak_session}
	map global user l %{: lsp-enable<ret>}
	# Enable logging since this is only for testing.
	set-option global lsp_cmd \"kak-lsp -s %val{session} -vvv --log ./log\"
"

cat > "$HOME"/.tmux.conf << EOF
# Pass escape through with little delay, as suggested by the Kakoune FAQ.
set -sg escape-time 25
EOF

cleanup() {
	if test -n "$cleanup_done"; then
		return
	fi
	$tmux kill-server ||:
	rm -rf "$HOME"
	cleanup_done=true
}
trap cleanup EXIT INT HUP TERM QUIT

# rust-analyzer needs a project.
cat > Cargo.toml << EOF
[package]
name = "example"
version = "0.1.0"
EOF

mkdir src
cat > src/main.rs << EOF
struct SomeStruct {
	some_field: bool
}
fn test() {
	let x = SomeStruct{some_field: false};
}
EOF

cat > local-kak-lsp.toml << EOF
[language.rust]
filetypes = ["rust"]
roots = ["."]
command = "rust-analyzer"
EOF

kak_startup_commands="$kak_startup_commands
set global lsp_cmd \"kak-lsp -c local-kak-lsp.toml -s %val{session} -vvv --log log\"
lsp-enable
lsp-diagnostic-lines-disable global
"

$tmux new-session -d kak  -e "$kak_startup_commands" src/main.rs

$tmux send-keys '/let x' Enter
sleep 4 # rust-analyzer can be slow to start up.
$tmux send-keys o x.

if test -n "$INTERACTIVE"; then
	$tmux attach
fi

sleep 4
$tmux capture-pane -p -S 3 -E 7

# CHECK: fn test() {
# CHECK: let x = SomeStruct{some_field: false};
# CHECK: x.
# CHECK: } {{ *}} into       Method{{.*}}
# CHECK: ~ {{ *}} some_field Field{{.*}}

}
```

</details>

**Comment by krobelus** [comment] 2021-09-04 19:53
Closing as I can't reproduce; please speak up if you can.

**Closed by krobelus** 2021-09-04 19:53 UTC
Labels: need steps to reproduce
