### ISSUE TITLE
Id : 0 when initializing language server

### ISSUE THREAD

**Issue by venotald** [kak-lsp/kak-lsp#408] opened 2020-10-11 11:49 UTC
I am trying to set up kak-lsp with an ada language server (https://github.com/AdaCore/ada_language_server)

I have added the the language server like this in kak-lsp.toml :
``` 
> [language.ada]
> filetypes = ["ada"]
> roots = [ ".gpr" ]
> command = "/home/My_Home/Applications/ada_language_server/linux/ada_language_server"
```
When editing an Ada file I get the following message : 
`Language server is not initialized, parking request`
And in the kak-lsp.log I have : 
```
>Oct 10 15:48:28.166 DEBG To server: {"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"textDocument":{"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"colorProvider":null,"completion":{"completionItem":{"documentationFormat":["plaintext"],"snippetSupport":true}},"semanticHighlightingCapabilities":{"semanticHighlighting":true}},"workspace":{"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","delete","rename"]}}},"processId":39379,"rootUri":"file:///home/My_Home/Dev_Workspace","trace":"off"},"id":0}, module: kak_lsp::language_server_transport:175
```
```
> Oct 10 15:48:28.209 DEBG From server: {"jsonrpc":"2.0","id":0,"error":{"code":-32602,"message":"SYSTEM.ASSERTIONS.ASSERT_FAILURE\n[/home/My_Home/Applications/ada_language_server/linux/libgnat-2020.so]\n0x7fd9b9620002\n[/home/My_Home/Applications/ada_language_server/linux/ada_language_server]\n0x6d9467\n0xacb970\n0xac225e\n0x6ea2f8\n0xacc2c8\n0xac354a\n0x6ebd23\n0xacc358\n0xac366a\n0x6ef046\n0xad7060\n0xa82fa0\n0xb64d3f\n0xb64600\n0xb925d7\n0xca0d0c\n0xcd6869\n0xcd993a\n0xcd3f1c\n0xcddd7d\n[/home/My_Home/Applications/ada_language_server/linux/libgnarl-2020.so]\n0x7fd9b9998958\n[/usr/lib/libpthread.so.0]\n0x7fd9b93593e7\n[/usr/lib/libc.so.6]\n0x7fd9b9265291\n0xfffffffffffffffe\n"}}, module: kak_lsp::language_server_transport:149
> Oct 10 15:48:28.209 ERRO Error response from server: Failure { jsonrpc: Some(V2), error: Error { code: InvalidParams, message: "SYSTEM.ASSERTIONS.ASSERT_FAILURE\n[/home/My_Home/Applications/ada_language_server/linux/libgnat-2020.so]\n0x7fd9b9620002\n[/home/My_Home/Applications/ada_language_server/linux/ada_language_server]\n0x6d9467\n0xacb970\n0xac225e\n0x6ea2f8\n0xacc2c8\n0xac354a\n0x6ebd23\n0xacc358\n0xac366a\n0x6ef046\n0xad7060\n0xa82fa0\n0xb64d3f\n0xb64600\n0xb925d7\n0xca0d0c\n0xcd6869\n0xcd993a\n0xcd3f1c\n0xcddd7d\n[/home/My_Home/Applications/ada_language_server/linux/libgnarl-2020.so]\n0x7fd9b9998958\n[/usr/lib/libpthread.so.0]\n0x7fd9b93593e7\n[/usr/lib/libc.so.6]\n0x7fd9b9265291\n0xfffffffffffffffe\n", data: None }, id: Num(0) }, module: kak_lsp::controller:127
> Oct 10 15:48:28.209 DEBG To editor `39337`: lsp-show-error 'ada language server error: ''SYSTEM.ASSERTIONS.ASSERT_FAILURE
```

Is `"id":0` coming from a lack in my configuration or something else ?

**Comment by krobelus** [comment] 2020-10-13 05:31
`SYSTEM.ASSERTIONS.ASSERT_FAILURE` comes from `libgnat-2020.so` which is used by the language server.
It looks like the language server is crashing.

> roots = [ ".gpr" ]

This should probably be `*.gpr`.

According to https://github.com/AdaCore/ada_language_server/blob/a5504542f3229110e30096a3fccab63a9d7ca018/doc/settings.md#projectfile that should work if you have a single project file, otherwise you need to figure out how to send configuration options.

**Comment by venotald** [comment] 2020-10-13 10:42
> This should probably be *.gpr.

I changed it with no success.

In the log, the issue seems to be the **id:0** in the message from kak-lsp to the ada_language_server which inded raise an exception in the server.
The value can be found at the end of the line.

**Comment by venotald** [comment] 2020-10-15 18:15
From what I have read at https://microsoft.github.io/language-server-protocol/ the Id parameter is used to match request answer with the server.

For a reason I can't explain, as I am not fluent enough in rust, the initialize request is send to the server while the **Id** is still at his default value (0). `,"id":0}`

**Comment by krobelus** [comment] 2020-10-15 19:09
Idk, with `rls` I also get an id of 0 for an initial request:

```
Oct 15 21:01:34.377 DEBG To server: {"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"textDocument":{"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"dynamicRegistration":false,"isPreferredSupport":false},"codeLens":{"dynamicRegistration":false},"colorProvider":{"dynamicRegistration":false},"completion":{"completionItem":{"commitCharactersSupport":false,"deprecatedSupport":false,"documentationFormat":["plaintext"],"preselectSupport":false,"snippetSupport":false},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]},"contextSupport":false,"dynamicRegistration":false},"declaration":{"dynamicRegistration":false,"linkSupport":false},"definition":{"dynamicRegistration":false,"linkSupport":false},"documentHighlight":{"dynamicRegistration":false},"documentLink":{"dynamicRegistration":false,"tooltipSupport":false},"documentSymbol":{"dynamicRegistration":false},"formatting":{"dynamicRegistration":false},"hover":{"contentFormat":["plaintext"],"dynamicRegistration":false},"implementation":{"dynamicRegistration":false,"linkSupport":false},"onTypeFormatting":{"dynamicRegistration":false},"publishDiagnostics":{"relatedInformation":false},"rangeFormatting":{"dynamicRegistration":false},"references":{"dynamicRegistration":false},"rename":{"dynamicRegistration":false,"prepareSupport":false},"semanticHighlightingCapabilities":{"semanticHighlighting":true},"semanticTokens":{"dynamicRegistration":false,"formats":["relative"],"requests":{"full":true,"range":false},"tokenModifiers":[],"tokenTypes":[]},"signatureHelp":{"contextSupport":false,"dynamicRegistration":false,"signatureInformation":{"documentationFormat":["plaintext"],"parameterInformation":{"labelOffsetSupport":false}}},"synchronization":{"didSave":true,"dynamicRegistration":false,"willSave":false,"willSaveWaitUntil":false},"typeDefinition":{"dynamicRegistration":false,"linkSupport":false}},"window":{"workDoneProgress":false},"workspace":{"applyEdit":false,"configuration":false,"didChangeConfiguration":{"dynamicRegistration":false},"executeCommand":{"dynamicRegistration":false},"symbol":{"dynamicRegistration":false,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"workspaceEdit":{"documentChanges":true,"failureHandling":"abort","resourceOperations":["create","delete","rename"]},"workspaceFolders":false}},"clientInfo":{"name":"kak-lsp","version":"8.0.0-snapshot"},"processId":402512,"rootUri":"file:///home/johannes/.cargo/registry/src/github.com-1ecc6299db9ec823/lsp-types-0.80.0","trace":"off"},"id":0}, module: kak_lsp::language_server_transport:175
Oct 15 21:01:34.410 DEBG From server: {"jsonrpc":"2.0","id":0,"result":{"capabilities":{"textDocumentSync":2,"hoverProvider":true,"completionProvider":{"resolveProvider":true,"triggerCharacters":[".",":"]},"definitionProvider":true,"implementationProvider":true,"referencesProvider":true,"documentHighlightProvider":true,"documentSymbolProvider":true,"workspaceSymbolProvider":true,"codeActionProvider":true,"codeLensProvider":{"resolveProvider":false},"documentFormattingProvider":true,"documentRangeFormattingProvider":false,"renameProvider":true,"executeCommandProvider":{"commands":["rls.applySuggestion-402517","rls.deglobImports-402517"]}}}}, module: kak_lsp::language_server_transport:149
```

I doubt that's really a problem, unless the language server failure is because of that.
Does the language server work in another editor?
I'll try..

**Comment by krobelus** [comment] 2020-10-15 19:36
Good news: I can reproduce on kak-lsp 8.0.0, but it works on the [development version](https://github.com/kak-lsp/kak-lsp#from-the-source). 

---

I downloaded `linux-latest-dbg.tar.gz` from the nightly packages https://bintray.com/reznikmm/ada-language-server/ada-language-server#files. It seems to work with your configuration. 
I created a file `x.adb`. (I have the gcc-ada frontend installed to test it.)

```ada
with Ada.Text_IO; use Ada.Text_IO;
procedure x is
begin
   Put_Line ("Hello WORLD!");
end x;
```

I can move the cursor to `Put_Line` and use `gd` to jump to its definition. (No need for a gpr file).

**Comment by venotald** [comment] 2020-10-15 20:02
Yes, I have the 8.0.0-1 installed via the Manjaro package. 

If I use plug.kak I will get the development version ?

**Comment by krobelus** [comment] 2020-10-15 20:44
Yeah, plug.kak gets the latest master branch by default. You probably need to run `cargo install --locked --force --path .` in `~/.config/kak/plugins/kak-lsp` after updating.
Also make sure that the resulting `~/.local/bin/kak-lsp` is used, either via PATH, or the `lsp_cmd` option.

**Comment by venotald** [comment] 2020-10-17 17:07
I no longer have crash or  `Language server is not initialized, parking request` message but it does not seem to be working when I use `gd`. 
Is there something I am missing ?

**Comment by krobelus** [comment] 2020-10-18 07:42
Here is the log I get when I edit above file and use `gd` on `Put_Line`.
I started Kakoune as `kak -s foo ada/x.adb -e 'set buffer filetype ada; lsp-enable'`.
The line second to last has the results (which is empty for you). Are you using the gcc frontend? Is there still an error message from the server?

It also works with [Neovim](https://github.com/AdaCore/ada_language_server#integration-with-languageclient-neovim) for me. If it it doesn't for you, it's definitely a server issue.

```
Oct 18 09:22:16.908 INFO Starting main event loop, module: kak_lsp::session:29
Oct 18 09:22:16.909 DEBG Searching for vars starting with KAK_LSP_PROJECT_ROOT_ADA, module: kak_lsp::project_root:46
Oct 18 09:22:16.909 DEBG Routing editor request to Route { session: "foo", language: "ada", root: "/home/johannes/git/kak-lsp/ada" }, module: kak_lsp::session:95
Oct 18 09:22:16.909 DEBG Spawning a new controller for Route { session: "foo", language: "ada", root: "/home/johannes/git/kak-lsp/ada" }, module: kak_lsp::session:117
Oct 18 09:22:16.910 INFO Starting Language server `/home/johannes/git/kak-lsp/linux/ada_language_server `, module: kak_lsp::language_server_transport:21
Oct 18 09:22:16.912 DEBG To editor `foo`: eval -client client0 'lsp-get-server-initialization-options ''/tmp/kak-lsp/johannes/85bfc72d1526e56d''', module: kak_lsp::editor_transport:85
Oct 18 09:22:16.917 DEBG lsp_server_initialization_options:
, module: kak_lsp::general:419
Oct 18 09:22:16.917 DEBG To server: {"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"textDocument":{"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"dynamicRegistration":false,"isPreferredSupport":false},"codeLens":{"dynamicRegistration":false},"colorProvider":{"dynamicRegistration":false},"completion":{"completionItem":{"commitCharactersSupport":false,"deprecatedSupport":false,"documentationFormat":["plaintext"],"preselectSupport":false,"snippetSupport":false},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]},"contextSupport":false,"dynamicRegistration":false},"declaration":{"dynamicRegistration":false,"linkSupport":false},"definition":{"dynamicRegistration":false,"linkSupport":false},"documentHighlight":{"dynamicRegistration":false},"documentLink":{"dynamicRegistration":false,"tooltipSupport":false},"documentSymbol":{"dynamicRegistration":false},"formatting":{"dynamicRegistration":false},"hover":{"contentFormat":["plaintext"],"dynamicRegistration":false},"implementation":{"dynamicRegistration":false,"linkSupport":false},"onTypeFormatting":{"dynamicRegistration":false},"publishDiagnostics":{"relatedInformation":false},"rangeFormatting":{"dynamicRegistration":false},"references":{"dynamicRegistration":false},"rename":{"dynamicRegistration":false,"prepareSupport":false},"semanticHighlightingCapabilities":{"semanticHighlighting":true},"semanticTokens":{"dynamicRegistration":false,"formats":["relative"],"requests":{"full":true,"range":false},"tokenModifiers":[],"tokenTypes":[]},"signatureHelp":{"contextSupport":false,"dynamicRegistration":false,"signatureInformation":{"documentationFormat":["plaintext"],"parameterInformation":{"labelOffsetSupport":false}}},"synchronization":{"didSave":true,"dynamicRegistration":false,"willSave":false,"willSaveWaitUntil":false},"typeDefinition":{"dynamicRegistration":false,"linkSupport":false}},"window":{"workDoneProgress":false},"workspace":{"applyEdit":false,"configuration":false,"didChangeConfiguration":{"dynamicRegistration":false},"executeCommand":{"dynamicRegistration":false},"symbol":{"dynamicRegistration":false,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"workspaceEdit":{"documentChanges":true,"failureHandling":"abort","resourceOperations":["create","delete","rename"]},"workspaceFolders":false}},"clientInfo":{"name":"kak-lsp","version":"8.0.0-snapshot"},"processId":468125,"rootUri":"file:///home/johannes/git/kak-lsp/ada","trace":"off"},"id":0}, module: kak_lsp::language_server_transport:175
Oct 18 09:22:16.983 DEBG From server: {"jsonrpc":"2.0","id":0,"result":{"capabilities":{"textDocumentSync":2,"completionProvider":{"triggerCharacters":[".","("],"resolveProvider":false},"hoverProvider":true,"declarationProvider":true,"definitionProvider":true,"typeDefinitionProvider":true,"implementationProvider":true,"referencesProvider":true,"documentSymbolProvider":true,"codeActionProvider":{"codeActionKinds":["refactor.rewrite"]},"documentFormattingProvider":true,"renameProvider":{},"foldingRangeProvider":true,"executeCommandProvider":{"commands":["als-named-parameters","als-refactor-imports"]},"workspaceSymbolProvider":true,"callHierarchyProvider":{},"alsCalledByProvider":true,"alsCallsProvider":true,"alsShowDepsProvider":true,"alsReferenceKinds":["reference","access","write","call","dispatching call","parent","child"]}}}, module: kak_lsp::language_server_transport:149
Oct 18 09:22:16.984 DEBG To server: {"jsonrpc":"2.0","method":"initialized","params":{}}, module: kak_lsp::language_server_transport:175
Oct 18 09:22:16.984 DEBG To server: {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"languageId":"ada","text":"with Ada.Text_IO; use Ada.Text_IO;\nprocedure x is\nbegin\n   Put_Line (\"Hello WORLD!\");\nend x;\n\n","uri":"file:///home/johannes/git/kak-lsp/ada/x.adb","version":1}}}, module: kak_lsp::language_server_transport:175
Oct 18 09:22:17.129 DEBG From server: {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///home/johannes/git/kak-lsp/ada/x.adb","diagnostics":[]}}, module: kak_lsp::language_server_transport:149
Oct 18 09:22:17.130 DEBG From server: {"jsonrpc":"2.0","id":2,"method":"window/workDoneProgress/create","params":{"token":"ada_ls-468132-indexing-1"}}, module: kak_lsp::language_server_transport:149
Oct 18 09:22:17.130 DEBG From server: {"jsonrpc":"2.0","method":"$/progress","params":{"token":"ada_ls-468132-indexing-1","value":{"kind":"begin","title":"Indexing","percentage":0}}}, module: kak_lsp::language_server_transport:149
Oct 18 09:22:17.130 DEBG From server: {"jsonrpc":"2.0","method":"$/progress","params":{"token":"ada_ls-468132-indexing-1","value":{"kind":"end"}}}, module: kak_lsp::language_server_transport:149
Oct 18 09:22:17.130 WARN Unsupported method: window/workDoneProgress/create, module: kak_lsp::controller:314
Oct 18 09:22:17.130 WARN Unsupported method: $/progress, module: kak_lsp::controller:377
Oct 18 09:22:17.130 WARN Unsupported method: $/progress, module: kak_lsp::controller:377
Oct 18 09:22:17.130 DEBG To editor `foo`: 
        eval -buffer '/home/johannes/git/kak-lsp/ada/x.adb' 'set buffer lsp_diagnostic_error_count 0
         set buffer lsp_diagnostic_warning_count 0
         set buffer lsp_errors 1 
         eval "set buffer lsp_error_lines 1  ''0| ''"
         set buffer lsp_diagnostics 1 ', module: kak_lsp::editor_transport:85
Oct 18 09:22:20.147 DEBG From editor: 
session   = "foo"
client    = "client0"
buffile   = "/home/johannes/git/kak-lsp/ada/x.adb"
filetype  = "ada"
version   = 1
method    = "textDocument/definition"
[params.position]
line      = 4
column    = 4
, module: kak_lsp::editor_transport:125
Oct 18 09:22:20.147 DEBG Searching for vars starting with KAK_LSP_PROJECT_ROOT_ADA, module: kak_lsp::project_root:46
Oct 18 09:22:20.148 DEBG Routing editor request to Route { session: "foo", language: "ada", root: "/home/johannes/git/kak-lsp/ada" }, module: kak_lsp::session:95
Oct 18 09:22:20.148 DEBG To server: {"jsonrpc":"2.0","method":"textDocument/definition","params":{"position":{"character":3,"line":3},"textDocument":{"uri":"file:///home/johannes/git/kak-lsp/ada/x.adb"}},"id":1}, module: kak_lsp::language_server_transport:175
Oct 18 09:22:20.153 DEBG From server: {"jsonrpc":"2.0","id":1,"result":[{"uri":"file:///usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/adainclude/a-textio.ads","range":{"start":{"line":507,"character":13},"end":{"line":507,"character":21}}}]}, module: kak_lsp::language_server_transport:149
Oct 18 09:22:20.153 DEBG To editor `foo`: eval -client client0 'evaluate-commands -try-client %opt{jumpclient} %{edit ''/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/adainclude/a-textio.ads'' 508 14}', module: kak_lsp::editor_transport:85
```

**Comment by krobelus** [comment] 2021-09-04 21:25
Closing as I can't reproduce, maybe try with a minimal configuration, see https://github.com/kak-lsp/kak-lsp#troubleshooting

**Closed by krobelus** 2021-09-04 21:25 UTC
Labels: bug, need steps to reproduce
