### ISSUE TITLE
kak-lsp process stays running and consumes a lot of CPU

### ISSUE THREAD

**Issue by maximbaz** [kak-lsp/kak-lsp#78] opened 2018-07-25 21:03 UTC
I'm not sure how I got into this state, I'll try to come up with repro steps. But for now see the picture, it is filtered for `kak`, and there are no `kak` processes running, but a bunch of `kak-lsp`.

![image](https://user-images.githubusercontent.com/1177900/43227110-093ed1f4-905e-11e8-8a42-f032cabf6985.png)

**Comment by ul** [comment] 2018-07-26 02:52
Wow, that's wrong and definitely should be fixed. I would appreciate steps for reproducing it because I don't remember hitting such situation by myself.

**Comment by maximbaz** [comment] 2018-07-26 11:43
Just an update, I've seen it happen one more time today, this time it was one hanging kak-lsp process, it was not consuming CPU and it was attached to a real file (not `*scratch*` buffer as on screenshot). But I'm still not sure how to reproduce this behavior on purpose.

**Comment by maximbaz** [comment] 2018-07-26 11:51
This is not how I achieved this state in the real life, but it also gets you to a hanging kak-lsp process, maybe the root cause is similar:

terminal 1: start kak
terminal 2: open htop, observe `kak` and `kak-lsp` processes
terminal 3: run `killall kak`
terminal 2: observe that `kak` disappears, but `kak-lsp` stays running.

**Comment by ul** [comment] 2018-07-26 11:57
It is expected that kak-lsp doesn't quit immediately when Kakoune is aborted because there is no reliable and easy way to track Kakoune process. `timeout` option exists exactly because of this.

What is not normal is when there are multiple kak-lsp processes for the same session and/or they hog CPU.

**Comment by maximbaz** [comment] 2018-07-26 12:03
Ah, I thought hanging processes is also an issue, but I see now that this is not the case 🙂. 

I'll keep an eye on the CPU usage, if that happens again I'll let you know. Maybe worth closing the ticket since it is not actionable at the moment.

**Comment by maximbaz** [comment] 2018-08-02 10:59
I've been monitoring this for a week and haven't seen this happen again.

**Comment by ul** [comment] 2018-11-29 19:19
Hey @maximbaz, I can't investigate it right now and I'm going offline for few days, I think it doesn't worth to torture your laptop with the process eating all CPU during this time.

I think I almost understand why it happens, it's situation @matklad warned me about. I fixed it partially, but need to work more on proper thread management. I'll prioritise this bug once I'm back to keyboard.

**Comment by maximbaz** [comment] 2018-11-29 20:59
> I can't investigate it right now and I'm going offline for few days, I think it doesn't worth to torture your laptop with the process eating all CPU during this time.

No worries, I actually paused the process as soon as I detected it, so it wasn't consuming CPU 🙂 But I will have to reboot soon, so it will be gone anyway.

Anyways, enjoy your offline time, I'm happy to hear that you know what to do about this issue 🙂

**Comment by ul** [comment] 2018-12-18 02:43
I think I found the only place where `loop` could go tight and eat CPU. @maximbaz please let me know if you'll experience this problem again.

Moved crossbeam_channel upgrade into a separate issue #144.

**Comment by supermarin** [comment] 2019-01-24 21:42
Wanted to open an issue about this for a while, and just found this. Been experiencing this for a month or so, seen both with python lang server and cquery.

<img width="557" alt="screen shot 2019-01-24 at 13 40 16" src="https://user-images.githubusercontent.com/627285/51710385-e8792e00-1fdd-11e9-9d5f-df4b0f6019c6.png">

**Comment by supermarin** [comment] 2019-01-28 19:36
@ul can we reopen just for tracking?

**Comment by ul** [comment] 2019-01-28 20:35
Yes, sure, sorry for the lag with the response. It looks like easily reproducible on your system, doesn't it? Could you describe the environment and how you run kak-lsp and integrate it into Kakoune?

**Comment by supermarin** [comment] 2019-01-29 00:48
>  It looks like easily reproducible on your system, doesn't it?
I see it on average once every 8h of coding

>  Could you describe the environment and how you run kak-lsp and integrate it into Kakoune?
I'm on OSX 10.14.1 (Mojave),  built both kakoune and kak-lsp from source with the newest rust toolchain. I mostly encounter this when working with `pyls`, probably because I spend the most time in kakoune/kak-lsp writing Python.

Since I'm newer to Kakoune, I haven't optimized session reusing yet I do launch/close more than 1 editor session on the same project. Possibly it gets stuck somewhere with closing sessions.

Regarding kak/kak-lsp integration, nothing too special:
```
# LSP
define-command lspe %{
    eval %sh{kak-lsp --kakoune -s $kak_session}
    lsp-enable
}
```
I don't start kak-lsp immediately on editor launch, but on demand `:lspe`.

**Comment by supermarin** [comment] 2019-01-29 00:50
Also, pretty sure I've observed this both in virtualenv and outside; need to confirm that one. For sure it does happen when venv is activated.

**Comment by supermarin** [comment] 2019-01-30 16:59
Sharing here - yesterday I've implemented proper kakoune session sharing and didn't run into this.
Perhaps try working for a day on the same project with > 1 kakoune session (open tmux splits and launch kak manually).

**Comment by losnappas** [comment] 2019-04-28 16:28
I think this happens when I first start a kakoune daemon with `kak -d -s abc` and then keep rejoining that with `kak -c abc`. Now `kak-lsp --kakoune -s $kak_session` creates a new lsp process but the previous ones never exit since the daemon never exits. Then I start getting "waiting for shell to finish process" message and things jam until I kill kak-lsp. Haven't noticed CPU going to 100%, though. And it doesn't happen every time, either, just sometimes. Might be a separate issue, but this seems close enough.

**Comment by ul** [comment] 2019-07-18 10:52
Hey folks, I will be grateful to hear if this problem is still occurring on the latest master (I believe that I fixed a couple of deadlocks in #144).

**Comment by pickfire** [comment] 2020-07-08 14:29
I opened `*scratch*` without any files and it have this behavior too.

**Comment by krobelus** [comment] 2021-12-14 11:37
a couple of issues have been fixed, please speak up if you hit something like this again

**Closed by krobelus** 2021-12-14 11:37 UTC
Labels: bug, need steps to reproduce
