### ISSUE TITLE
kak-lsp v8.0.0 with clangd v11.0.0 not working

### ISSUE THREAD

**Issue by gman0** [kak-lsp/kak-lsp#430] opened 2020-12-22 12:25 UTC
kak-lsp is no longer working after the latest clangd update and I get "parking request" message in kakoune:

**Versions:**

```
$ kak -version
Kakoune v2020.09.01
```

```
$ kak-lsp --version
kak-lsp 8.0.0
```

```
$ clangd --version
clangd version 11.0.0
```

**Configuration:**

```
$ cat ~/.config/kak-lsp/kak-lsp.toml
[language.go]
filetypes = ["go"]
roots = ["Gopkg.toml", "go.mod", ".git", ".hg"]
command = "gopls"
offset_encoding = "utf-8"

[language.c_cpp]
filetypes = ["c", "cpp"]
roots = ["compile_commands.json"]
command = "clangd"
```

**Logs:**

Running kak-lsp with `-vvv` and clangd with `--log=verbose`.

```
Dec 21 13:16:20.880 INFO Starting main event loop, module: kak_lsp::session:29
Dec 21 13:16:20.880 DEBG Searching for vars starting with KAK_LSP_PROJECT_ROOT_C_CPP, module: kak_lsp::project_root:41
Dec 21 13:16:20.880 DEBG Routing editor request to Route { session: "11127", language: "c_cpp", root: "<REDACTED>" }, module: kak_lsp::session:95
Dec 21 13:16:20.880 DEBG Spawning a new controller for Route { session: "11127", language: "c_cpp", root: "<REDACTED>" }, module: kak_lsp::session:117
Dec 21 13:16:20.880 INFO Starting Language server `clangd --log=verbose`, module: kak_lsp::language_server_transport:21
Dec 21 13:16:20.881 DEBG To editor `11127`: lsp-get-server-initialization-options '/tmp/kak-lsp/gman/85949eecdb949fea', module: kak_lsp::editor_transport:85
Dec 21 13:16:20.889 DEBG lsp_server_initialization_options:
, module: kak_lsp::general:192
Dec 21 13:16:20.889 DEBG To server: {"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"textDocument":{"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"colorProvider":null,"completion":{"completionItem":{"documentationFormat":["plaintext"],"snippetSupport":false}},"semanticHighlightingCapabilities":{"semanticHighlighting":true}},"workspace":{"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","delete","rename"]}}},"processId":11205,"rootUri":"file://<REDACTED>","trace":"off"},"id":0}, module: kak_lsp::language_server_transport:175
Dec 21 13:16:20.916 DEBG From server: {"id":0,"jsonrpc":"2.0","result":{"capabilities":{"codeActionProvider":{"codeActionKinds":["quickfix","refactor","info"]},"completionProvider":{"allCommitCharacters":[" ","\t","(",")","[","]","{","}","<",">",":",";",",","+","-","/","*","%","^","&","#","?",".","=","\"","'","|"],"resolveProvider":false,"triggerCharacters":[".","<",">",":","\"","/"]},"declarationProvider":true,"definitionProvider":true,"documentFormattingProvider":true,"documentHighlightProvider":true,"documentLinkProvider":{"resolveProvider":false},"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"\n","moreTriggerCharacter":[]},"documentRangeFormattingProvider":true,"documentSymbolProvider":true,"executeCommandProvider":{"commands":["clangd.applyFix","clangd.applyTweak"]},"hoverProvider":true,"referencesProvider":true,"renameProvider":true,"selectionRangeProvider":true,"semanticHighlighting":{"scopes":[["variable.other.cpp"],["variable.other.local.cpp"],["variable.parameter.cpp"],["entity.name.function.cpp"],["entity.name.function.method.cpp"],["entity.name.function.method.static.cpp"],["variable.other.field.cpp"],["variable.other.field.static.cpp"],["entity.name.type.class.cpp"],["entity.name.type.enum.cpp"],["variable.other.enummember.cpp"],["entity.name.type.typedef.cpp"],["entity.name.type.dependent.cpp"],["entity.name.other.dependent.cpp"],["entity.name.namespace.cpp"],["entity.name.type.template.cpp"],["entity.name.type.concept.cpp"],["storage.type.primitive.cpp"],["entity.name.function.preprocessor.cpp"],["meta.disabled"]]},"semanticTokensProvider":{"full":{"delta":true},"legend":{"tokenModifiers":[],"tokenTypes":["variable","variable","parameter","function","member","function","member","variable","class","enum","enumConstant","type","dependent","dependent","namespace","typeParameter","concept","type","macro","comment"]},"range":false},"signatureHelpProvider":{"triggerCharacters":["(",","]},"textDocumentSync":{"change":2,"openClose":true,"save":true},"typeHierarchyProvider":true,"workspaceSymbolProvider":true},"serverInfo":{"name":"clangd","version":"clangd version 11.0.0"}}}, module: kak_lsp::language_server_transport:149
Dec 21 13:16:20.917 INFO Waiting for Messages to language server to finish..., module: kak_lsp::thread_worker:18
Dec 21 13:16:20.917 DEBG Received signal to stop language server, closing pipe, module: kak_lsp::language_server_transport:186
Dec 21 13:16:20.917 DEBG Waiting for language server process end, module: kak_lsp::language_server_transport:81
Dec 21 13:16:20.919 ERRO Language server error: I[13:16:20.916] clangd version 11.0.0
I[13:16:20.916] PID: 11213
I[13:16:20.916] Working directory: <redacted>
I[13:16:20.916] argv[0]: clangd
I[13:16:20.916] argv[1]: --log=verbose
V[13:16:20.916] User config file is /home/gman/.config/clangd/config.yaml
I[13:16:20.916] Starting LSP over stdin/stdout
V[13:16:20.916] <<< {"id":0,"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"textDocument":{"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"colorProvider":null,"completion":{"completionItem":{"documentationFormat":["plaintext"],"snippetSupport":false}},"semanticHighlightingCapabilities":{"semanticHighlighting":true}},"workspace":{"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","delete","rename"]}}},"processId":11205,"rootUri":"file://<REDACTED>","trace":"off"}}

I[13:16:20.916] <-- initialize(0)
I[13:16:20.916] --> reply:initialize(0) 0 ms
V[13:16:20.916] >>> {"id":0,"jsonrpc":"2.0","result":{"capabilities":{"codeActionProvider":{"codeActionKinds":["quickfix","refactor","info"]},"completionProvider":{"allCommitCharacters":[" ","\t","(",")","[","]","{","}","<",">",":",";",",","+","-","/","*","%","^","&","#","?",".","=","\"","'","|"],"resolveProvider":false,"triggerCharacters":[".","<",">",":","\"","/"]},"declarationProvider":true,"definitionProvider":true,"documentFormattingProvider":true,"documentHighlightProvider":true,"documentLinkProvider":{"resolveProvider":false},"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"\n","moreTriggerCharacter":[]},"documentRangeFormattingProvider":true,"documentSymbolProvider":true,"executeCommandProvider":{"commands":["clangd.applyFix","clangd.applyTweak"]},"hoverProvider":true,"referencesProvider":true,"renameProvider":true,"selectionRangeProvider":true,"semanticHighlighting":{"scopes":[["variable.other.cpp"],["variable.other.local.cpp"],["variable.parameter.cpp"],["entity.name.function.cpp"],["entity.name.function.method.cpp"],["entity.name.function.method.static.cpp"],["variable.other.field.cpp"],["variable.other.field.static.cpp"],["entity.name.type.class.cpp"],["entity.name.type.enum.cpp"],["variable.other.enummember.cpp"],["entity.name.type.typedef.cpp"],["entity.name.type.dependent.cpp"],["entity.name.other.dependent.cpp"],["entity.name.namespace.cpp"],["entity.name.type.template.cpp"],["entity.name.type.concept.cpp"],["storage.type.primitive.cpp"],["entity.name.function.preprocessor.cpp"],["meta.disabled"]]},"semanticTokensProvider":{"full":{"delta":true},"legend":{"tokenModifiers":[],"tokenTypes":["variable","variable","parameter","function","member","function","member","variable","class","enum","enumConstant","type","dependent","dependent","namespace","typeParameter","concept","type","macro","comment"]},"range":false},"signatureHelpProvider":{"triggerCharacters":["(",","]},"textDocumentSync":{"change":2,"openClose":true,"save":true},"typeHierarchyProvider":true,"workspaceSymbolProvider":true},"serverInfo":{"name":"clangd","version":"clangd version 11.0.0"}}}

E[13:16:20.917] Transport error: Input/output error
I[13:16:20.917] LSP finished, exiting with status 1
, module: kak_lsp::language_server_transport:52
Dec 21 13:16:20.919 DEBG Language server closed pipe, stopping reading, module: kak_lsp::language_server_transport:127
Dec 21 13:16:21.917 INFO ... Messages to language server terminated with ok, module: kak_lsp::thread_worker:20
Dec 21 13:16:21.917 INFO Waiting for Messages from language server to finish..., module: kak_lsp::thread_worker:18
Dec 21 13:16:21.917 INFO ... Messages from language server terminated with ok, module: kak_lsp::thread_worker:20
Dec 21 13:16:21.917 INFO Waiting for Language server errors to finish..., module: kak_lsp::thread_worker:18
Dec 21 13:16:21.917 INFO ... Language server errors terminated with ok, module: kak_lsp::thread_worker:20
Dec 21 14:21:30.898 DEBG From editor: 
session  = "11127"
client   = ""
buffile  = ""
filetype = ""
version  = 0
method   = "stop"
[params]
, module: kak_lsp::editor_transport:125
Dec 21 14:21:30.898 INFO Shutting down language servers and exiting, module: kak_lsp::session:180
Dec 21 14:21:30.898 ERRO Failed to send stop message to language server, module: kak_lsp::session:183
Dec 21 14:21:30.898 INFO Exit c_cpp in project <REDACTED>, module: kak_lsp::session:185
Dec 21 14:21:30.898 INFO Waiting for Controller to finish..., module: kak_lsp::thread_worker:18
Dec 21 14:21:30.898 INFO ... Controller terminated with err, module: kak_lsp::thread_worker:20
Dec 21 14:21:30.899 INFO Waiting for Messages to editor to finish..., module: kak_lsp::thread_worker:18
Dec 21 14:21:30.899 INFO ... Messages to editor terminated with ok, module: kak_lsp::thread_worker:20
```

---

**Other details:**

I've installed kakoune and kak-lsp from Manjaro repositories. Building kak-lsp from source (HEAD at 34e888eea109ad1b2fbaee3b0b7afab46b38f1c8) makes things work again.

**Comment by krobelus** [comment] 2020-12-22 19:41
Duplicate of #425

**Closed by krobelus** 2020-12-22 19:41 UTC

**Comment by krobelus** [comment] 2020-12-22 19:42
Thanks for the report - since this is fixed in master there's not really anything left to do.
