### ISSUE TITLE
ccls completion incorrect

### ISSUE THREAD

**Issue by Luis-Hebendanz** [kak-lsp/kak-lsp#275] opened 2020-01-07 16:33 UTC
Hello there,
I wanted to thank you for this nice addon! 

If ccls is used, and I select a completion item from the list while I am writing a function the whole function with its signature is being used not only the function name.

![image](https://user-images.githubusercontent.com/22085373/71911479-09e21400-3174-11ea-8325-42fe55264e50.png)

![image](https://user-images.githubusercontent.com/22085373/71911635-5af20800-3174-11ea-8e2d-404d8d8b63dd.png)

**Comment by topisani** [comment] 2020-01-08 14:40
Are you sure you are using an up to date `kak-lsp` build? i used to get this when the label was just used for insertion, but that behavior has been changed some time ago

**Comment by Luis-Hebendanz** [comment] 2020-01-08 22:29
```
$ kak-lsp --version 
kak-lsp 7.0.0
```

**Comment by ul** [comment] 2020-01-16 22:18
It seems to be the latest release version not master (which should report `kak-lsp 7.0.0-snapshot`). @topisani how recent is the change you are referring to? Do you refer your work on snippets?

The latest release tho should ask language server to provide non-snippet labels by default via the client capabilities. However, it might be the case that language server ignores it.

**Comment by topisani** [comment] 2020-01-17 09:47
I think this is related to the `insert_text` vs `label` usage. It might have been broken with my recent snippets support, but I wouldn't have thought so. It might also be something with ccls' `detailedLabel` setting, I think this does something to that extend...

**Comment by arrufat** [comment] 2020-01-17 12:35
I can confirm that it does not work as of https://github.com/ul/kak-lsp/commit/a7960510e7320cae5a980c1105660bfc900f779e.

The `detailedLabel` flag does not change that.

**Comment by krobelus** [comment] 2021-09-16 20:42
Duplicate of #40

**Closed by krobelus** 2021-09-16 20:42 UTC

**Comment by krobelus** [comment] 2021-09-16 20:43
we fall back to the label when we get a text edit that we can't handle yet
however, common cases are already supported by #326 
(also clangd doesn't seem to have this problem, probably it doesn't force us to use textEdit)
