### ISSUE TITLE
kak-lsp change utf-8 character "❌" by "M-oM-?-="

### ISSUE THREAD

**Issue by sucrecacao** [kak-lsp/kak-lsp#391] opened 2020-09-03 22:01 UTC
# Steps
open a kak python buffer, enable lsp.

write:
```
print("❌
foo")
```
put the cursor on the ❌  line and add space at the end of the line ( play a bit around with the cursor if it doesn't work)

# expected
❌ stay the same 

# Outcome 
❌ get replaced by `Mo-M?M-=

![utf8_kak_bug](https://user-images.githubusercontent.com/55893070/92177964-cdb99d00-ee41-11ea-9564-e4d6b91818eb.png)

**Comment by krobelus** [comment] 2020-09-25 17:54
I can't reproduce with pyls. Maybe a debug log with `-vv` or `-vvv` can give insight?

**Comment by sucrecacao** [comment] 2020-09-27 21:01
Ok, I can't reproduce neither. Don't know what was going on.

**Comment by krobelus** [comment] 2020-12-31 15:09
I can reproduce with a file containing only 🐛 - the [bug emoji](https://unicode-table.com/en/1F41B/).

```
echo 🐛 > repro.py
# or, equivalently with bash's printf:
printf '\U1f41b\n' > repro.py
```

I did not yet find a valid Python program that reproduces the issue.

**Comment by gustavo-hms** [comment] 2021-02-17 14:21
Hi, folks!

This is not a Python specific issue, but something related to multi byte chars. Apparently, `kak-lsp` doesn't play well with Unicode in some corner cases. Here is a minimal Go snippet showing the same issue. You can reproduce it using `gopls` in the default configuration shipped with `kak-lsp`:

```go
package main

import "fmt"

func main() {
    somevar := 17
    fmt.Println("Some quote: “the expected value is %d”", |)
}
```

The `|` (pipe) represents the cursor position. Now, start typing `somevar` at the cursor position. `kak-lsp` will try to suggest `somevar` as a completion candidate and the behaviour described by @sucrecacao can be observed.

**Comment by mreppen** [comment] 2021-03-23 04:17
I noticed a similar issue in another context. IIRC, the unicode character was "replaced" only with certain highlighters. More importantly, the file contents did indeed have the correct character.

If it's a highlighter issue, it would explain why only some can reproduce.

**Comment by gustavo-hms** [comment] 2021-03-23 12:10
By the way, I see it's still marked as `need steps to reproduce`. Aren't the steps I provided enough? In any case, I'm pretty sure you can reproduce it with any file with a line containing multi byte characters, regardless of its file type, provided there's a language server for it obviously.

**Comment by mreppen** [comment] 2021-03-23 14:53
At least in my case, neither the original, your, nor the 🐛 example reproduces the problem.

As I said, I saw a similar issue before (also with “ and ”) and it appeared only with certain highlighters. Therefore I suspect it won't be reproducible without sharing a minimal kakrc that reproduces.

**Comment by krobelus** [comment] 2021-03-23 19:09
@gustavo-hms thanks, I can reproduce with your example

**Comment by krobelus** [comment] 2022-12-30 16:14
I think this is fixed

**Closed by krobelus** 2022-12-30 16:14 UTC
Labels: bug
